h <- c(0,0,0,0,1,1,1,1)
f <- c(0,0,1,1,0,0,1,1)
p <- c(0,1,0,1,0,1,0,1)
X <- cbind(1, h, f, p, h*f, h*p, f*p, h*f*p)
ratio <- (h+1)/(f+1)
cat("X1/X2 values:", ratio, "\n")
cat("Coefficients:", solve(X, ratio), "\n")
cat("Reconstruction:", as.vector(X %*% solve(X, ratio)), "\n")
cat("Max error:", max(abs(X %*% solve(X, ratio) - ratio)), "\n")
