---
title: "Mental Health Data Application"
author: "Name: Ming-Ju Chuang"
header-includes:
- \usepackage{xeCJK}
- \setCJKmainfont{標楷體}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
- \usepackage{float}
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    toc: no
---

```{r setup, include=FALSE}
options(knitr.kable.NA = '')
knitr::opts_chunk$set(echo = FALSE, fig.height = 10, fig.width = 16, fig.align = "center")

# devtools::install_github("LukeChuang890212/EBMR_Methods_Reproducibility_Materials/EBMRalgorithm")
library(EBMRalgorithm)
# library(torch)

library(tidyverse)
library(kableExtra)

library(ggplot2)
library(ggpubr)

library(numDeriv)
library(Matrix)
library(nnet)
```

# Read data

```{r}
source("Data_application.r")
```

```{r}
original_data = read.csv("data_application.csv")
percent = original_data$Percentage
n = 2486
class_n = round(n*percent/100)

gen_data = function(original_data, class_n){
  dat = matrix(NA, n, 5)
  for(i in 1:nrow(original_data)){
    dat[((sum(class_n[0:(i-1)]))+1):sum(class_n[1:i]),] = matrix(rep(unlist(original_data[i,]), each = class_n[i]), class_n[i], 5)
  }
  dat = as.data.frame(dat[, -5])
  
  dat[dat == "Yes"] = 1
  dat[dat == "No"] = 0
  dat[dat == "Abnormal"] = 1
  dat[dat == "Normal"] = 0
  dat[dat == "Missing"] = NA
  colnames(dat) = c("father", "health", "teacher_report", "parent_report")
  dat$r = ifelse(is.na(dat$teacher_report), 0, 1)
  dat$father = as.numeric(dat$father)
  dat$health = as.numeric(dat$health)
  dat$parent_report = as.numeric(dat$parent_report)
  dat$teacher_report = as.numeric(dat$teacher_report)
  dat$fp = dat$father*(1-dat$parent_report)
  dat$fp2 = (1-dat$father)*(1-dat$parent_report)
  
  dat$teacher_report[dat$r == 0] = -1
  dat$y = dat$teacher_report
  return(dat)
}

dat = gen_data(original_data, class_n)

model = multinom(as.factor(y)~as.factor(father)+as.factor(parent_report)+as.factor(health), data = dat)
outcome_distr = predict(model, newdata = dat, type = "probs")
```

# Data description:

# Some primary analysis:

```{r}
n = nrow(dat)
missing_rate = 1-mean(dat$r)
mu_cc = mean(dat$teacher_report[dat$r == 1])
se_cc = sd(dat$teacher_report[dat$r == 1])/sqrt(sum(dat$r))
```

# Analysis with our proposed methods

```{r}
bootstrap = function(full_ps_specifications, W, data, B, init.list){
  library(foreach)
  library(doParallel)
  library(doSNOW)
  library(EBMRalgorithm)
  
  n = nrow(data)
  
  cores = detectCores()
  cl = makeCluster(cores - 4) ## number of clusters 
  registerDoSNOW(cl)
  
  pb = txtProgressBar(max = B, style = 3)
  progress <- function(n) setTxtProgressBar(pb, n)
  opts = list(progress = progress)
  parallel_packages = c("EBMRalgorithm", "stringr", "Matrix", "numDeriv")
  
  boot_result = foreach(i= 1:B, .combine = 'cbind', .options.snow = opts, .packages = parallel_packages, .export = c("effect.f", "delta_method")) %dopar% {
    result = tryCatch({
      indices = sample(1:n, replace = TRUE)
      boot_dat = data[indices,]
      
      theta.hat = se_theta.hat = rep(NA, 7)
      w.hat.list = list(w.hat1 = c(), w.hat2 = c(), w.hat3 = c(), w.hat4 = c(), w.hat5 = c(), w.hat6 = c(), w.hat7 = c())
      nu.hat.list = list(nu.hat1 = c(), nu.hat2 = c(), nu.hat3 = c(), nu.hat4 = c(), nu.hat5 = c(), nu.hat6 = c(), nu.hat7 = c())
      k = 1
      for(model_num in 1:3){
        model_combinations = combn(3, model_num)
        for(i in 1:ncol(model_combinations)){
          model_set = model_combinations[, i]
          print(c(model_num, i))
          
          p.hat = se_p.hat = p_cc = se_p_cc = rep(NA, 2)
          w.hat = nu.hat = c()
          for(l in 1:2){
            sub_boot_dat = boot_dat[boot_dat$health == (l-1),]
            
            ps_specifications <- list(
              formula.list = full_ps_specifications$formula.list[model_set],
              h_x_names.list = full_ps_specifications$h_x_names.list[model_set],
              alpha_init.list = init.list[[l]][model_set],
              inv_link = full_ps_specifications$inv_link
            )
            
            ebmr = EBMRAlgorithm$new("teacher_report", ps_specifications, sub_boot_dat, W)
            result = ebmr$EBMR_IPW(h_x_names = c("father", "parent_report"), 
                                   nu_init = c(1, rep(0, model_num - 1)),
                                   true_ps =  NULL)
      
            # ps_fit.list = list()
            # J = length(ps_specifications$formula.list)
            # for(j in 1:J){
            #   formula = ps_specifications$formula.list[[j]]
            #   h_x_names = ps_specifications$h_x_names.list[[j]]
            #   inv_link = ps_specifications$inv_link
            #   ps_fit.list[[j]] = WangShaoKim2014(formula, h_x_names, inv_link, W = W, data = sub_boot_dat)
            # }
            # 
            # # if(model_num == 3) print(ps_fit.list[[2]]$coefficients)
            # result = EBMR_IPW(h_x_names = c("father", "parent_report"), W = W, data = sub_boot_dat, se.fit = TRUE)
            
            p.hat[l] = result$mu_ipw
            p_cc[l] = mean(sub_boot_dat$teacher_report[sub_boot_dat$r == 1])
            se_p.hat[l] = result$se_ipw
            se_p_cc[l] = sd(sub_boot_dat$teacher_report[sub_boot_dat$r == 1])/sqrt(sum(sub_boot_dat$r == 1))
            w.hat = c(w.hat, result$w.hat)
            nu.hat = c(nu.hat, result$nu.hat)
          }
          
          theta.hat[k] = effect.f(p.hat[1], p.hat[2])
          theta_cc = effect.f(p_cc[1], p_cc[2])
          se_theta.hat[k] = sqrt((delta_method(p.hat[1], p.hat[2])^2)%*%(se_p.hat^2))
          se_theta_cc = sqrt(delta_method(p_cc[1], p_cc[2])%*%(se_p_cc^2))
          w.hat.list[[k]] = w.hat
          nu.hat.list[[k]] = nu.hat
          
          k = k + 1
        }
      }
      
      # ebmr = EBMRAlgorithm$new(y_names = "teacher_report",
      #                          ps_specifications = ps_specifications,
      #                          data = boot_dat)
      # result = ebmr$EBMR_IPW(h_x_names = c("father", "parent_report"))
      # result$w.hat
      # cor(result$ps.matrix)
      # ebmr$ps_fit.list[[3]]$coefficients
      # ebmr$ps_fit.list[[3]]$se
      # estimates = unlist(result[c(1, 3)])
      # estimates
      
      c(theta.hat = theta.hat, theta_cc = theta_cc, se_theta.hat = se_theta.hat, se_theta_cc = se_theta_cc,
        unlist(w.hat.list), unlist(nu.hat.list))
    }, error = function(e){
      c(theta.hat = NA, theta_cc = NA, se_theta.hat = NA, se_theta_cc = NA)
    })
  }
  gc()
  return(boot_result)
}
```

```{r}
perturb_bootstrap = function(full_ps_specifications, W, data, B){
  library(foreach)
  library(doParallel)
  library(doSNOW)
  library(EBMRalgorithm)
  
  n = nrow(data)
  # rgen = function(n) sample(c(-1, 1), size = n, replace = TRUE)
  rgen = function(n) rexp(n)
  
  cores = detectCores()
  cl = makeCluster(cores - 4) ## number of clusters 
  registerDoSNOW(cl)
  
  pb = txtProgressBar(max = B, style = 3)
  progress <- function(n) setTxtProgressBar(pb, n)
  opts = list(progress = progress)
  parallel_packages = c("EBMRalgorithm", "stringr", "Matrix", "numDeriv")
  
  boot_result = foreach(i= 1:B, .combine = 'cbind', .options.snow = opts, .packages = parallel_packages, .export = c("WangShaoKim2014", "ensemble", "estimate_nu", "WangShaoKim2014_perturb", "EBMR_IPW_perturb", "estimate_nu_perturb", "ensemble_perturb", "parse_formula", "separate_variable_types", "effect.f", "delta_method")) %dopar% {
    result = tryCatch({
      wt = rexp(n)
      
      theta.hat = se_theta.hat = rep(NA, 7)
      w.hat.list = list(w.hat1 = c(), w.hat2 = c(), w.hat3 = c(), w.hat4 = c(), w.hat5 = c(), w.hat6 = c(), w.hat7 = c())
      nu.hat.list = list(nu.hat1 = c(), nu.hat2 = c(), nu.hat3 = c(), nu.hat4 = c(), nu.hat5 = c(), nu.hat6 = c(), nu.hat7 = c())
      k = 1
      for(model_num in 1:3){
        model_combinations = combn(3, model_num)
        for(i in 1:ncol(model_combinations)){
          model_set = model_combinations[, i]
          print(c(model_num, i))
          
          ps_specifications <- list(
            formula.list = full_ps_specifications$formula.list[model_set],
            h_x_names.list = full_ps_specifications$h_x_names.list[model_set],
            inv_link = full_ps_specifications$inv_link
          )
          
          p.hat = se_p.hat = p_cc = se_p_cc = rep(NA, 2)
          w.hat = nu.hat = c()
          for(l in 1:2){
            subdat = data[data$health == (l-1),]
            subwt = wt[data$health == (l-1)]
            ps_fit.list = list()
            J = length(ps_specifications$formula.list)
            for(j in 1:J){
              formula = ps_specifications$formula.list[[j]]
              h_x_names = ps_specifications$h_x_names.list[[j]]
              inv_link = ps_specifications$inv_link
              ps_fit.list[[j]] = WangShaoKim2014_perturb(formula, h_x_names, inv_link, W, data = subdat, subwt, se.fit = F)
              # ps_fit.list[[j]] = WangShaoKim2014(formula, h_x_names, inv_link, W = W, data = subdat)
            }
            
            result = EBMR_IPW_perturb(h_x_names = c("father", "parent_report"), W, data = subdat, subwt, se.fit = F)
            
            p.hat[l] = result$mu_ipw
            se_p.hat[l] = result$se_ipw
            w.hat = c(w.hat, result$w.hat)
            nu.hat = c(nu.hat, result$nu.hat)
            
            subwt_cc = wt[data$health == (l-1) & data$r == 1]
            p_cc[l] = mean(subwt_cc*subdat$teacher_report[subdat$r == 1])
            se_p_cc[l] = sd(subdat$teacher_report[subdat$r == 1])/sqrt(sum(subdat$r == 1))
          }
          
          theta.hat[k] = effect.f(p.hat[1], p.hat[2])
          theta_cc = effect.f(p_cc[1], p_cc[2])
          se_theta.hat[k] = sqrt((delta_method(p.hat[1], p.hat[2])^2)%*%(se_p.hat^2))
          se_theta_cc = sqrt(delta_method(p_cc[1], p_cc[2])%*%(se_p_cc^2))
          w.hat.list[[k]] = w.hat
          nu.hat.list[[k]] = nu.hat
          
          k = k + 1
        }
      }
      
      # ebmr = EBMRAlgorithm$new(y_names = "teacher_report",
      #                          ps_specifications = ps_specifications,
      #                          data = boot_dat)
      # result = ebmr$EBMR_IPW(h_x_names = c("father", "parent_report"))
      # result$w.hat
      # cor(result$ps.matrix)
      # ebmr$ps_fit.list[[3]]$coefficients
      # ebmr$ps_fit.list[[3]]$se
      # estimates = unlist(result[c(1, 3)])
      # estimates
      
      c(theta.hat = theta.hat, theta_cc = theta_cc, se_theta.hat = se_theta.hat, se_theta_cc = se_theta_cc,
        unlist(w.hat.list), unlist(nu.hat.list))
    }, error = function(e){
      NA
    })
  }
  return(boot_result)
}
```

```{r}
rm.extreme = function(v){
  z.score = scale(v)
  extreme_num = sum(abs(z.score) > 4)
  print(paste(extreme_num, length(v)))
  if(extreme_num == 0){
    return(v)
  }else{
    return(v[-order(abs(z.score), decreasing = TRUE)[1:min(extreme_num, extreme_num)]])
  }
}
```

```{r}
summary.gmm = function(ps_fit.list){
  alpha.list = lapply(ps_fit.list, function(ps_fit) ps_fit$coef)
  alpha_se.list = lapply(ps_fit.list, function(ps_fit) ps_fit$se)
  for(i in 1:length(alpha.list)){
    alpha.list[[i]] = rbind(alpha.list[[i]], alpha_se.list[[i]]) 
    p.value = (1-pnorm(abs(alpha.list[[i]][1,]/alpha.list[[i]][2,])))*2
    alpha.list[[i]] = rbind(alpha.list[[i]], p.value)
    rownames(alpha.list[[i]]) = c("Estimate", "SE", "p-value")
    colnames(alpha.list[[i]]) = c("Intercept", "teacher_report", ps_fit.list[[i]]$model_x_names)
  }
  # par(mfrow = c(1, 2))
  # boxplot(est.res$pi.m, ylim = c(0, 1))
  # boxplot(est.res$pi.m%*%est.res$w.pi, ylim = c(0, 1))
  return(alpha.list)
}
```

## Analysis

### Estimation

```{r}
# source("C:/Users/stat-pc/Desktop/NTHU_Research/EBMR_Methods_Reproducibility_Materials/Simulation_Studies/test_methods.r")
# source("C:/Users/stat-pc/Desktop/NTHU_Research/EBMR_Methods_Reproducibility_Materials/Simulation_Studies/test_methods.r")
```

```{r}
#------------------------------------------------------------------------------#
# Basic Setup ----
#------------------------------------------------------------------------------#
full_ps_specifications = list(
  formula.list = list(
    r ~ o(teacher_report) + father,
    r ~ o(teacher_report) + parent_report,
    r ~ o(teacher_report)
  ),
  h_x_names.list = list(
    c("father", "parent_report"),
    c("father", "parent_report"),
    c("father", "parent_report")
  ),
  inv_link = function(eta) 1/(1+exp(eta))
)

# OR5
# W = function(g.matrix){
#   return(diag(ncol(g.matrix)))
# }

# OR6
W = function(g.matrix){
  return(solve(t(g.matrix)%*%g.matrix/nrow(g.matrix)))
}

health = 0:1
subset_names = c("health0", "health1")

effect.f = function(x, y) log((y/(1-y))/(x/(1-x)))
delta_method = function(x, y) c(-(y/(1-y))/((x/(1-x))^2)*((1/x^2)/((1/x-1)^2)),
                                ((1/y^2)/((1/y-1)^2))/(x/(1-x)))/exp(effect.f(x, y))

# effect.f = function(x, y) (y/(1-y))/(x/(1-x))
# delta_method = function(x, y) c(-(y/(1-y))/((x/(1-x))^2)*((1/x^2)/((1/x-1)^2)),
#                                 ((1/y^2)/((1/y-1)^2))/(x/(1-x)))

boot = TRUE
B = 1000
```

```{r, eval = FALSE}
#------------------------------------------------------------------------------#
# Estimate p_0 and p_1 using all combinations of the candidate models
#------------------------------------------------------------------------------#
ps_fit.list0 = list()
ps_fit.list1 = list()
nu_hat0 = NULL
nu_hat1 = NULL

for(model_num in 1:3){
  model_combinations = combn(3, model_num)
  for(i in 1:ncol(model_combinations)){
    model_set = model_combinations[, i]
    for(k in 1:length(health)){
      # if((4 %in% model_set)) next
      print(c(k, model_set))
      subdat = dat[dat$health == health[k], ]
      subdat$y = subdat$teacher_report
      
      ps_specifications <- list(
          formula.list = full_ps_specifications$formula.list[model_set],
          h_x_names.list = full_ps_specifications$h_x_names.list[model_set],
          inv_link = full_ps_specifications$inv_link
        )
      
      ebmr = EBMRAlgorithm$new("teacher_report", ps_specifications, subdat, W)
      result = ebmr$EBMR_IPW(h_x_names = c("father", "parent_report"),
                             true_ps =  NULL)

      save_file = paste0(c("MHD_results/EBMR_IPW_", subset_names[k], "_", model_set, "_W_optimal_OR8.RDS"), collapse = "")
      # saveRDS(result, save_file)
      
      if(model_num == 3){
        if(k == 1){
          ps_fit.list0 = ebmr$ps_fit.list; nu_hat0 = result$nu.hat;
        }else{
          ps_fit.list1 = ebmr$ps_fit.list; nu_hat1 = result$nu.hat;
        }
      } 
    }
  }
}
```

```{r}
summary.gmm(ps_fit.list0)
summary.gmm(ps_fit.list1)
```

```{r}
nu_hat0
nu_hat1
```

```{r}
#------------------------------------------------------------------------------#
# Bootstrap ----
#------------------------------------------------------------------------------#
dat$y = dat$teacher_report

init.list = list(
  alpha_init.list0 = list(
    c(-0.3834341, 1.07945126, -0.1318883),
    c(-4.2670736, 5.9582123, -0.5972129),
    c(-0.58007379, 1.30964808)
  ),
  alpha_init.list1 = list(
    c(0.09019492, -1.511548 -0.3946616),
    c(-1.969056, 3.5823611, -1.37232734),
    c(-0.290583706, -0.7607009)
  )
)
  
# boot_result = perturb_bootstrap(full_ps_specifications, W, dat, B)
set.seed(20200525)
boot_result = bootstrap(full_ps_specifications, W, dat, B, init.list)
# boot_result = parametric_bootstrap(outcome_distr, full_ps_specifications, W, dat, B)
save.file = paste0(c("MHD_results/EBMR_IPW_bootstrap_W_optimal_OR9.RDS"), collapse = "")
# save.file = paste0(c("MHD_results/EBMR_IPW_perturb_bootstrap_W_identity_OR9.RDS"), collapse = "")
# save.file = paste0(c("MHD_results/EBMR_IPW_perturb_bootstrap_W_identity_OR10.RDS"), collapse = "")
# if(file.exists(save.file)){
#   boot_result = cbind(readRDS(save.file), boot_result)
#   saveRDS(boot_result, save.file)
# }else{
#   saveRDS(boot_result, save.file)
# }
saveRDS(boot_result, save.file)
print(sum(is.na(boot_result[1,])))
print(apply(boot_result, 1, mean, na.rm = T))
print(apply(boot_result, 1, sd, na.rm = T))
################################################################################
```

### Results with optimal W and standard bootstrap

```{r}
effect.f = function(x, y) log((y/(1-y))/(x/(1-x)))
delta_method = function(x, y) c(-(y/(1-y))/((x/(1-x))^2)*((1/x^2)/((1/x-1)^2)),
                                ((1/y^2)/((1/y-1)^2))/(x/(1-x)))/exp(effect.f(x, y))

# effect.f = function(x, y) (y/(1-y))/(x/(1-x))
# delta_method = function(x, y) c(-(y/(1-y))/((x/(1-x))^2)*((1/x^2)/((1/x-1)^2)),
#                                 ((1/y^2)/((1/y-1)^2))/(x/(1-x)))
```

```{r}
all_results = matrix(NA, 8, 2)
k = 1
for(model_num in 1:3){
  model_combinations = combn(3, model_num)
  for(i in 1:ncol(model_combinations)){
    all_estimates = matrix(NA, length(health), 2)
    model_set = model_combinations[, i]
    # if((4 %in% model_set0) || !(1 %in% model_set0)) next
    result0 = readRDS(paste0(c("MHD_results/EBMR_IPW_", subset_names[1], "_", model_set, "_W_optimal_OR8.RDS"), collapse = ""))
    all_estimates[1, ] = unlist(result0[c(1, 3)])

    result1 = readRDS(paste0(c("MHD_results/EBMR_IPW_", subset_names[2], "_", model_set, "_W_optimal_OR8.RDS"), collapse = ""))
    all_estimates[2, ] = unlist(result1[c(1, 3)])

    effect = effect.f(all_estimates[1, 1], all_estimates[2, 1])
    Sigma = matrix(c(all_estimates[1, 2]^2, 0, 0, all_estimates[2, 2]^2), 2,2)
    se = sqrt(delta_method(all_estimates[1, 1], all_estimates[2, 1])%*%Sigma%*%delta_method(all_estimates[1, 1], all_estimates[2, 1]))
      
      # effect = all_estimates[2, 1] - all_estimates[1, 1]
      # se = sqrt(all_estimates[1, 2]^2+all_estimates[2, 2]^2)
      
    all_results[k, ] = c(effect, se)
    k = k + 1
  }
}
cc1 = dat$health == 1 & dat$r == 1
cc0 = dat$health == 0 & dat$r == 1
mu_cc1 = mean(dat[cc1, ]$teacher_report)
se_cc1 = sd(dat[cc1, ]$teacher_report)/sqrt(sum(cc1))
mu_cc0 = mean(dat[cc0, ]$teacher_report)
se_cc0 = sd(dat[cc0, ]$teacher_report)/sqrt(sum(cc0))
Sigma = matrix(c(se_cc0^2, 0, 0, se_cc1^2), 2,2)
all_results[8, ] = c(effect.f(mu_cc0, mu_cc1),
             sqrt(delta_method(mu_cc0, mu_cc1)%*%Sigma%*%delta_method(mu_cc0, mu_cc1)))
# all_results[20,] = c(mu_cc1-mu_cc0, sqrt(se_cc1^2+se_cc0^2))
all_results
# res.tmp = res
```

```{r, fig.width=10, fig.height=20}
rm.extreme = function(v){
  # v = v[v < quantile(v, 0.98)]
  # return(v)
  iqr <- IQR(v)

  # Identify the values outside the lower and upper bounds
  lower_bound <- quantile(v, 0.25) - 3 * iqr
  upper_bound <- quantile(v, 0.75) + 3 * iqr

  # Exclude the extreme values
  return(v[v >= lower_bound & v <= upper_bound])
}
make_w_labels <- function(num_str) {
  nums <- as.integer(strsplit(num_str, "")[[1]])
  parse(text = paste0("w[", nums, "]"))
}

make_nu_labels <- function(num_str) {
  nums <- as.integer(strsplit(num_str, "")[[1]])
  parse(text = paste0("nu[", nums, "]"))
}

boot_result = readRDS(paste0(c("MHD_results/EBMR_IPW_bootstrap_W_optimal_OR9.RDS"), collapse = ""))
model_combinations = c("1", "2", "3", "12", "13", "23", "123")
boot_effect_se = rep(NA, 8)
# boot_se_se = rep(NA, 8)
layout_matrix = matrix(nrow = 14, ncol = 6)
for(i in 1:7){
  layout_matrix[2*(i-1)+1, 1:6] = i+6*(i-1)
  layout_matrix[2*(i-1)+2,] = (i+6*(i-1)+1):(i+6*(i-1)+6)
}
layout(layout_matrix, heights = rep(c(1, 5), 7))
for(k in 1:7){
  par(mar = c(0, 0, 2, 0)) 
  plot.new()
  title(paste("model set:", model_combinations[k]), cex.main = 1.5)
  
  par(mar = c(4, 2, 2, 2), pty = "s") 
  theta.hat = paste0("theta.hat", k)
  se_theta.hat = paste0("se_theta.hat", k)
  w.hat = rownames(boot_result)[grepl(paste0("w.hat", k), rownames(boot_result))]
  nu.hat = rownames(boot_result)[grepl(paste0("nu.hat", k), rownames(boot_result))]
  w.hat1 = w.hat[1:(length(w.hat)/2)]
  w.hat2 = w.hat[(length(w.hat)/2+1):length(w.hat)]
  nu.hat1 = nu.hat[1:(length(nu.hat)/2)]
  nu.hat2 = nu.hat[(length(nu.hat)/2+1):length(nu.hat)]
  qqnorm(rm.extreme(boot_result[theta.hat, !is.na(boot_result[theta.hat,])]), main = expression(hat(theta)))
  # boot_effect_se[k] = sd(rm.extreme(boot_result[theta.hat, !is.na(boot_result[theta.hat,])]))
  boot_effect_se[k] = sd(boot_result[theta.hat, ], na.rm = T)
  qqnorm(rm.extreme(boot_result[se_theta.hat, !is.na(boot_result[se_theta.hat,])]), main = expression(widehat("SE")(hat(theta))))
  if(length(w.hat) == 2){
    plot.new()
    plot.new()
    plot.new()
    plot.new()
  }else{
    boxplot(t(boot_result[w.hat1,]), main = expression(paste(hat(bold(w)), " for ", p[0])), 
            names = make_w_labels(model_combinations[k]))
    boxplot(t(boot_result[w.hat2,]), main = expression(paste(hat(bold(w)), " for ", p[1])),
            names = make_w_labels(model_combinations[k]))
    boxplot(t(boot_result[nu.hat1,]), main = expression(paste(hat(bold(nu)), " for ", p[0])), 
            names = make_nu_labels(model_combinations[k]))
    boxplot(t(boot_result[nu.hat2,]), main = expression(paste(hat(bold(nu)), " for ", p[1])),
            names = make_nu_labels(model_combinations[k]))
  }
  
  # abline(v = all_results[k, 2], col = 2, lwd = 2.5)
  # boot_se_se[k] = quantile(rm.extreme_se(boot_result[3, !is.na(boot_result[3,])]), .95)
}
boot_effect_se[8] = sd(rm.extreme(boot_result["theta_cc", !is.na(boot_result["theta_cc",])]))
# boot_se_se[8] = quantile(rm.extreme_se(boot_result["se_theta_cc", !is.na(boot_result["se_theta_cc",])]), .95)
boot_effect_se
# boot_se_se
```

```{r}
full_results = cbind(all_results, boot_effect_se)
full_results = as.data.frame(full_results)
full_results = cbind(round(full_results, 3),
                    apply(cbind(full_results[, 1] - qnorm(0.975)*full_results[, 2], 
                                full_results[, 1] + qnorm(0.975)*full_results[, 2]), 1, 
                          function(v) paste0("[", round(v[1], 3) , ", ", round(v[2], 3), "]")))

rownames(full_results) = c("$\\hat{\\theta}_{100}$","$\\hat{\\theta}_{010}$", "$\\hat{\\theta}_{001}$",
                          "$\\hat{\\theta}_{110}$", "$\\hat{\\theta}_{101}$", "$\\hat{\\theta}_{011}$",
                          "$\\hat{\\theta}_{111}$", "$\\hat{\\theta}_\\text{CC}$")
colnames(full_results) = c("PE", "SE", "Bootstrap SE", "$95\\%$ CI")
kable(full_results, align = "c", booktabs = TRUE, escape = FALSE, linesep = "",
      caption = "") %>%
  kable_styling(full_width = F, latex_options = c("hold_position")) 
```

### Results with optimal W and perturbation bootstrap

```{r}
effect.f = function(x, y) log((y/(1-y))/(x/(1-x)))
delta_method = function(x, y) c(-(y/(1-y))/((x/(1-x))^2)*((1/x^2)/((1/x-1)^2)),
                                ((1/y^2)/((1/y-1)^2))/(x/(1-x)))/exp(effect.f(x, y))

# effect.f = function(x, y) (y/(1-y))/(x/(1-x))
# delta_method = function(x, y) c(-(y/(1-y))/((x/(1-x))^2)*((1/x^2)/((1/x-1)^2)),
#                                 ((1/y^2)/((1/y-1)^2))/(x/(1-x)))
```

```{r}
all_results = matrix(NA, 8, 2)
k = 1
for(model_num in 1:3){
  model_combinations = combn(3, model_num)
  for(i in 1:ncol(model_combinations)){
    all_estimates = matrix(NA, length(health), 2)
    model_set = model_combinations[, i]
    # if((4 %in% model_set0) || !(1 %in% model_set0)) next
    result0 = readRDS(paste0(c("MHD_results/EBMR_IPW_", subset_names[1], "_", model_set, "_W_optimal_OR6.RDS"), collapse = ""))
    all_estimates[1, ] = unlist(result0[c(1, 3)])

    result1 = readRDS(paste0(c("MHD_results/EBMR_IPW_", subset_names[2], "_", model_set, "_W_optimal_OR6.RDS"), collapse = ""))
    all_estimates[2, ] = unlist(result1[c(1, 3)])

    effect = effect.f(all_estimates[1, 1], all_estimates[2, 1])
    Sigma = matrix(c(all_estimates[1, 2]^2, 0, 0, all_estimates[2, 2]^2), 2,2)
    se = sqrt(delta_method(all_estimates[1, 1], all_estimates[2, 1])%*%Sigma%*%delta_method(all_estimates[1, 1], all_estimates[2, 1]))
      
      # effect = all_estimates[2, 1] - all_estimates[1, 1]
      # se = sqrt(all_estimates[1, 2]^2+all_estimates[2, 2]^2)
      
    all_results[k, ] = c(effect, se)
    k = k + 1
  }
}
cc1 = dat$health == 1 & dat$r == 1
cc0 = dat$health == 0 & dat$r == 1
mu_cc1 = mean(dat[cc1, ]$teacher_report)
se_cc1 = sd(dat[cc1, ]$teacher_report)/sqrt(sum(cc1))
mu_cc0 = mean(dat[cc0, ]$teacher_report)
se_cc0 = sd(dat[cc0, ]$teacher_report)/sqrt(sum(cc0))
Sigma = matrix(c(se_cc0^2, 0, 0, se_cc1^2), 2,2)
all_results[8, ] = c(effect.f(mu_cc0, mu_cc1),
             sqrt(delta_method(mu_cc0, mu_cc1)%*%Sigma%*%delta_method(mu_cc0, mu_cc1)))
# all_results[20,] = c(mu_cc1-mu_cc0, sqrt(se_cc1^2+se_cc0^2))
all_results
# res.tmp = res
```

```{r, fig.width=10, fig.height=20}
rm.extreme_se = function(v){
  v = v[v < quantile(v, 0.98)]
  return(v)
}
make_w_labels <- function(num_str) {
  nums <- as.integer(strsplit(num_str, "")[[1]])
  parse(text = paste0("w[", nums, "]"))
}

make_nu_labels <- function(num_str) {
  nums <- as.integer(strsplit(num_str, "")[[1]])
  parse(text = paste0("nu[", nums, "]"))
}

boot_result = readRDS(paste0(c("MHD_results/EBMR_IPW_perturb_bootstrap_W_optimal_OR6.RDS"), collapse = ""))
model_combinations = c("1", "2", "3", "12", "13", "23", "123")
boot_effect_se = rep(NA, 8)
# boot_se_se = rep(NA, 8)
layout_matrix = matrix(nrow = 14, ncol = 6)
for(i in 1:7){
  layout_matrix[2*(i-1)+1, 1:6] = i+6*(i-1)
  layout_matrix[2*(i-1)+2,] = (i+6*(i-1)+1):(i+6*(i-1)+6)
}
layout(layout_matrix, heights = rep(c(1, 5), 7))
for(k in 1:7){
  par(mar = c(0, 0, 2, 0)) 
  plot.new()
  title(paste("model set:", model_combinations[k]), cex.main = 1.5)
  
  par(mar = c(4, 2, 2, 2), pty = "s") 
  theta.hat = paste0("theta.hat", k)
  se_theta.hat = paste0("se_theta.hat", k)
  w.hat = rownames(boot_result)[grepl(paste0("w.hat", k), rownames(boot_result))]
  nu.hat = rownames(boot_result)[grepl(paste0("nu.hat", k), rownames(boot_result))]
  w.hat1 = w.hat[1:(length(w.hat)/2)]
  w.hat2 = w.hat[(length(w.hat)/2+1):length(w.hat)]
  nu.hat1 = nu.hat[1:(length(nu.hat)/2)]
  nu.hat2 = nu.hat[(length(nu.hat)/2+1):length(nu.hat)]
  qqnorm(rm.extreme(boot_result[theta.hat, !is.na(boot_result[theta.hat,])]), main = expression(hat(theta)))
  boot_effect_se[k] = sd(rm.extreme(boot_result[theta.hat, !is.na(boot_result[theta.hat,])]))
  # qqnorm(rm.extreme(boot_result[se_theta.hat, !is.na(boot_result[se_theta.hat,])]), main = expression(widehat("SE")(hat(theta))))
  plot.new()
  if(length(w.hat) == 2){
    plot.new()
    plot.new()
    plot.new()
    plot.new()
  }else{
    boxplot(t(boot_result[w.hat1,]), main = expression(paste(hat(bold(w)), " for ", p[0])), 
            names = make_w_labels(model_combinations[k]))
    boxplot(t(boot_result[w.hat2,]), main = expression(paste(hat(bold(w)), " for ", p[1])),
            names = make_w_labels(model_combinations[k]))
    boxplot(t(boot_result[nu.hat1,]), main = expression(paste(hat(bold(nu)), " for ", p[0])), 
            names = make_nu_labels(model_combinations[k]))
    boxplot(t(boot_result[nu.hat2,]), main = expression(paste(hat(bold(nu)), " for ", p[1])),
            names = make_nu_labels(model_combinations[k]))
  }
  
  # abline(v = all_results[k, 2], col = 2, lwd = 2.5)
  # boot_se_se[k] = quantile(rm.extreme_se(boot_result[3, !is.na(boot_result[3,])]), .95)
}
boot_effect_se[8] = sd(rm.extreme(boot_result["theta_cc", !is.na(boot_result["theta_cc",])]))
# boot_se_se[8] = quantile(rm.extreme_se(boot_result["se_theta_cc", !is.na(boot_result["se_theta_cc",])]), .95)
boot_effect_se
# boot_se_se
```

```{r}
full_results = cbind(all_results, boot_effect_se)
full_results = as.data.frame(full_results)
full_results = cbind(round(full_results, 3),
                    apply(cbind(full_results[, 1] - qnorm(0.975)*full_results[, 2], 
                                full_results[, 1] + qnorm(0.975)*full_results[, 2]), 1, 
                          function(v) paste0("[", round(v[1], 3) , ", ", round(v[2], 3), "]")))

rownames(full_results) = c("$\\hat{\\theta}_{100}$","$\\hat{\\theta}_{010}$", "$\\hat{\\theta}_{001}$",
                          "$\\hat{\\theta}_{110}$", "$\\hat{\\theta}_{101}$", "$\\hat{\\theta}_{011}$",
                          "$\\hat{\\theta}_{111}$", "$\\hat{\\theta}_\\text{CC}$")
colnames(full_results) = c("PE", "SE", "Bootstrap SE", "$95\\%$ CI")
kable(full_results, align = "c", booktabs = TRUE, escape = FALSE, linesep = "",
      caption = "") %>%
  kable_styling(full_width = F, latex_options = c("hold_position")) 
```

## Sensitivity Analysis

### Estimation

```{r}
possibly_true_ps.vector = c(1, 1)
# exp_tilt_x_names = c("father", "parent_report")
exp_tilt_x_names = c("father", "parent_report")
xi.vector.list = list(
  xi.vector0 = seq(0, nrow(dat[dat$health == 0, ])^(-1/2), length.out = 30),
  xi.vector1 = seq(0, nrow(dat[dat$health == 1, ])^(-1/2), length.out = 30)
)
```

```{r}
for(k in 1:2){
  subdat = dat[dat$health == k-1, ]
  xi.vector = xi.vector.list[[k]]
  for(xi in xi.vector){
    print(c(xi, k))
      
    ps_specifications <- list(
        formula.list = full_ps_specifications$formula.list[1:3],
        h_x_names.list = full_ps_specifications$h_x_names.list[1:3],
        inv_link = full_ps_specifications$inv_link
      )
    ebmr = EBMRAlgorithm$new("teacher_report", ps_specifications, subdat, W)
    result = ebmr$EBMR_IPW(h_x_names = c("father", "parent_report"))
    
    # exp_tilt = function(y, x) exp(xi*as.matrix(cbind(y))%*%rep(1, ncol(cbind(y))))
    exp_tilt = function(y, x) exp(xi*as.matrix(cbind(y, x))%*%c(-1, 1, -1))
    sa_result = ebmr$EBMR_IPW_with_locally_misspecified_model(
      ps.matrix = result$ps.matrix,
      perturb_ps = possibly_true_ps.vector[k],
      exp_tilt = exp_tilt,
      exp_tilt_x_names = exp_tilt_x_names,
      h_x_names = c("father", "parent_report")
    )
    save_file = paste0(c("MHD_results/EBMR_IPW_", subset_names[k], "_", 1:3, "_mild", round(xi, 3), "_OR7.RDS"), collapse = "")
    saveRDS(sa_result, save_file)
  }
}
```


### Results

```{r}
all_results = matrix(NA, 30, 2)
m = 1
for(i in 1:30){
  all_estimates = matrix(NA, length(health), 2)
  for(k in 1:length(health)){
    xi = xi.vector.list[[k]][i]
    read_file = paste0(c("MHD_results/EBMR_IPW_", subset_names[k], "_", 1:3, "_mild", round(xi, 3), "_OR.RDS"), collapse = "")
    sa_result = readRDS(read_file)
    print(sa_result$w.hat)
    all_estimates[k, ] = unlist(sa_result[1:2])
  }
  effect = effect.f(all_estimates[1, 1], all_estimates[2, 1])
  Sigma = matrix(c(all_estimates[1, 2]^2, 0, 0, all_estimates[2, 2]^2), 2, 2)
  se = sqrt(delta_method(all_estimates[1, 1], all_estimates[2, 1])%*%Sigma%*%delta_method(all_estimates[1, 1], all_estimates[2, 1]))
  all_results[m, ] = c(effect, se)
  m = m + 1
}

range(all_results[, 1])

# Create the plot
plot(cbind(1:30, all_results[, 1]), type = "o",
     xlab = expression(xi), 
     ylab = "",  # Remove default ylab to add custom label
     las = 1)  # Ensure axis labels are horizontal

# Add the y-axis label manually with horizontal rotation
mtext(expression(hat(theta)), side = 2, line = 3, at = mean(par("usr")[3:4]), cex = 1, las = 1)
points(1:30, all_results[, 1], pch = 16)
abline(h = 1, lwd = 2)
```

# Analysis under MAR

```{r}
# Define the statistic function for bootstrap
theta_hat_fn <- function(data, indices) {
  boot_dat <- data[indices, ]
  
  fit0 = glm(1-r~father, data = boot_dat, family = binomial(), subset = health == 0)
  fit1 = glm(1-r~father, data = boot_dat, family = binomial(), subset = health == 1)
  
  ps0 = 1 - fitted(fit0)
  ps1 = 1 - fitted(fit1)
  
  p0_hat = mean(boot_dat$r[boot_dat$health == 0]/ps0*boot_dat$y[boot_dat$health == 0])
  p1_hat = mean(boot_dat$r[boot_dat$health == 1]/ps1*boot_dat$y[boot_dat$health == 1])
  theta.hat = effect.f(p0_hat, p1_hat)
  
  return(theta.hat)
}

theta.hat = theta_hat_fn(dat, 1:nrow(dat))
```

```{r}
library(boot)

# Run bootstrap
set.seed(123)
boot_res <- boot(dat, theta_hat_fn, R = 1000)

# Results
theta.hat <- boot_res$t0
se.theta <- sd(boot_res$t)
ci <- c(theta.hat - qnorm(0.975)*se.theta, theta.hat + qnorm(0.975)*se.theta)

theta.hat
se.theta
ci 
```



